version: '3'
services:
  postgres:
    image: postgres:12
    container_name: messenger-postgres
    command: -c max_connections=10
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    restart: always