CREATE TYPE STATUS AS ENUM ('online', 'offline');

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  username VARCHAR NOT NULL,
  phone VARCHAR UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  status STATUS NOT NULL DEFAULT 'offline',
  password VARCHAR NOT NULL,
  UNIQUE(phone)
);

CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY,
  content VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  sender_id UUID CONSTRAINT fk_sender_id REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  receiver_id UUID CONSTRAINT fk_receiver_id REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  seen BOOLEAN NOT NULL,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);
